[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.25"
serde = "1.0.219"
serde_json = "1.0.142"
solana-program = "2.3.0"
tokio = { version = "1", features = ["full"] } 
